### ISSUE TITLE
Existing components design review

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#1212]
- [ ] https://github.com/dxc-technology/halstack-react/issues/835
- [ ] https://github.com/dxc-technology/halstack-react/issues/836
- [x] https://github.com/dxc-technology/halstack-react/issues/840
- [ ] https://github.com/dxc-technology/halstack-react/issues/841
- [x] https://github.com/dxc-technology/halstack-react/issues/855
