### ISSUE TITLE
Improvements to documentation sites

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#813]
- [x] Automate the creation of technical doc based on typescript definitions
- [x] dxc-technology/halstack-style-guide#867
- [x] dxc-technology/halstack-style-guide#868
- [x] Deployment tasks
- [x] dxc-technology/halstack-style-guide#869
- [x] dxc-technology/halstack-style-guide#814 
- [x] #912 
- [x] #867
- [x] #980

## Effort
Design and define a re-structured IA (Information architecture), UI design and content design for the documentation sites. 
- Display component usage and specifications in different tabs 
- Improve component examples (Provide contextual cases where components can be used) 
- Updates on layout and responsiveness of the sites 
- Improve information “findability”  
- Add a changelog page with all the important design system updates 
- Evaluate adding analytics.

## Impact
**Product teams**: To have a more structured and easier to read documentation
