### ISSUE TITLE
[Site] Add overview pages to docs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-react#814]
- [x] dxc-technology/halstack-react#894
- [x] [Site] Add develop page to doc
- [x] [Site] Add contributing page to doc
