### ISSUE TITLE
Implement stand-alone website for Halstack guidelines

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#912]
## Epic description

Migration of the current site of the halstack design system to a more blended version between design and development aspects.

Link of the design draft: https://xd.adobe.com/view/80455b0e-566a-4a93-a3f9-c329f3be0230-d516/

- [x] dxc-technology/halstack-style-guide#717 
- [x] dxc-technology/halstack-style-guide#659
- [x] dxc-technology/halstack-react#814
- [x] dxc-technology/halstack-style-guide#843
- [x] dxc-technology/halstack-react#895
