### ISSUE TITLE
Review default theme for V5

### ISSUE THREAD

**Issue by jsardid** [dxc-technology/halstack-react#945]
- [x] Check missing components in default theme
- [x] Review theme builder
- [x] Review UX Config service
- [x] Update File Input tokens. [#865](https://github.com/dxc-technology/halstack-react/issues/865)

**Comment by Lisa159** [comment]
## Tokens review

- [ ] Remove calculated tokens for disabled state (except in toggle group).
- [ ] Add font color token to all components. This token should be used also in icons.

### Checkbox:
- [ ]  Add calculated value for hover (subLightness = 15).

### Date Input:
- [ ] Change tokens name: 
- BaseColor -> PickerSelectedDateBackgroundColor ?
- AccentColor -> PickerSelectedDateFontColor ?

### Dropdown:
- [ ] Apply fontColor to icon and caret.

### Paginator:
- [ ] Add `min-width: 82px;` to select components

### Select:
- [ ] FontColor should be applied to EVERYTHING. Placeholder should be calculated (set opacity 0.5).
- [ ] Rename baseColor to selectedOptionBackgroundColor. Hover calculado (sublightness 5) y active calculado (sublightness 10).

### Slider:
- [ ] Apply baseColor to focus state.

### Spinner:
- [ ] Advance theme: TrackCircleColorOnDark is not working. Maybe instead of 'onDark' change it to 'overlay'?

### Table:
- [ ] Add token for font color on header -> headerFontColor
- [ ] Add token for font color on cells-> cellFontColor

### ToggleGroup:
- [ ] On disabled, calculate color when selected. Unselected should not be calculated.

### Wizard:
- [ ] Add token for font selected step (inside the circle) -> SelectedFontColor
- [ ] Apply fontColor token to labels. Not visited labels should have 60% opacity.
