### ISSUE TITLE
Focus review

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-react#990]
Some component's focus can cause problems distinguishing the outline from the Halstack palette of colors. Others are implemented with box-shadow instead of outline, which can't have an offset to distinguish the focus styling, or they basically don't display the focus when they have been clicked (Switch and Checkbox) and others yes (Button, Text-Input, ...), etc. To establish a uniform focus styling and behaviour we must:

- [x] Update every focus style to (except Date input, Number input, Password input, Text input, Textarea, Select and Accordion):
```
outline: 2px solid #0095ff;
outline-offset: 2px;
```
- [x] Update Switch and Checkbox focus behaviour. They must display the focus when they have been clicked (this also includes the label `onClick`).
- [x] #987.
- [x] Update every storie that has been affected by all these changes.
- [ ] Document all these changes and bring them into the design libraries.

All these changes have force to update other components spacing (here are more details about it #991).

**Comment by jsardid** [comment]
Waiting for onDark strategy
